---
# chocomilk vars

# Package Changelog
changelog: 'https://help.airtame.com/general/product-changes'

# Regex for Version
version: "{{ register_changelog.content |
  regex_search('App[ |:]? v?\\d.\\d.\\d\\b') |
  regex_search('\\d.\\d.\\d\\b')
  }}"

# Download URL
url: 'https://downloads-cdn.airtame.com/app/latest/win/Airtame-{{ version }}-setup.msi'
# url64:

searchreplace:
  'tools/chocolateyinstall.ps1':
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)(".*")
      replace: '$urlPackage = "{{ url }}"'
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)(".*")
      replace: '$checksumPackage = "{{ file_hash }}"'

# readme to description
readme:
  start: 5
  end: 14

# deploy
deploy:
  - provider: chocolatey
    repository: "https://push.chocolatey.org/"
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: chocolatey
    repository: "https://nuget.itigo.tech/upload"
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.airtame.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://chat.open-circle.ch'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'notification-chocolatey'
